### ISSUE TITLE
any pretrained model?

### ISSUE THREAD

**Issue by xhsoldier** [fotisdr/pi-gan#1]
I trained the model, but the result is not as good as we expected.
Is there any pretrained model that I can test it?
thanks.

**Comment by fotisdr** [comment]
You should try tweaking the parameters of the `opts` variable in the training script in order to get a better model (the default ones are not necessarily good). For instance, you can try increasing the size of the kernel `opts ['g_enc_numkernels']` (e.g. to [16,16,32,32,64,64,128]).
